#!/usr/bin/env node

/**
 * Generates src/version.ts with the current package version.
 * Run as part of the build pipeline to avoid stale hardcoded version strings.
 */

const fs = require('fs');
const path = require('path');

const packageJson = require(path.resolve(__dirname, '..', 'package.json'));
const version = packageJson.version;

const content = `// Auto-generated by scripts/generate-version.js — do not edit manually
export const SDK_VERSION = '${version}';
`;

const outPath = path.resolve(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(outPath, content, 'utf-8');

console.log(`Generated src/version.ts with version ${version}`);
